#snc_redis:
#    clients:
#
#        # Define your clients here. The example below connects to database 0 of the default Redis server.
#        #
#        # See https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md for instructions on
#        # how to configure the bundle.
#        #
#        #        default:
#        #            type: phpredis
#        #            alias: default
#        #            dsn: "%env(REDIS_URL)%"
#        default:
#            type: predis
#            dsn: "%env(REDIS_URL)%"
#            alias: default
#        cache:
#            type: predis
#            alias: cache
#            dsn: "%env(REDIS_URL)%"
#            options:
#                profile: 2.2
#                connection_timeout: 10
#                read_write_timeout: 20
#        session:
#            type: predis
#            dsn: "%env(REDIS_URL)%"
#            alias: session
#    session:
#        client: session
#    doctrine:
#        metadata_cache:
#            client: cache
#            entity_manager: default             # the name of your entity_manager connection
#            document_manager: default           # the name of your document_manager connection
#        result_cache:
#            client: cache
#            entity_manager: [default, read]     # you may specify multiple entity_managers
#        query_cache:
#            client: cache
#            entity_manager: default
#        second_level_cache:
#            client: cache
#            entity_manager: default
