#controllers_admin:
#    resource: ../../src/Controller/Admin
#    type: rest
#    prefix: v1/admin

controllers_front:
    resource: ../../src/Controller/Front
    type: rest
    prefix: v1/public

controllers_restricted:
    resource: ../../src/Controller/Restricted
    type: rest
    prefix: v1/restricted

post_login_check:
    path: /v1/public/users/login_check
    methods: ['POST']
