<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;

/**
 * CampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class AbstractEntityRepository extends EntityRepository
{
    private static $unauthorizedKeys = array(
        'hint', 'hydrate', 'offset', 'limit', 'partial_load', 'asc', 'desc'
    );

    /**
     *
     * array criteria array($key => $value)
     * array joinColumn array($join, $alias, $conditionType, $condition, $indexBy)
     * @param array $criteria
     * @param array $joinColumn
     * @return mixed
     */
    public function findByCriteria(
        array $criteria = [],
        array $joinColumn = []
    ) {
        $queryBuilder = $this->createQueryBuilder('entity');

        $queryBuilder = $this->addWhere($queryBuilder, $criteria);

        $queryBuilder = $this->createJoin($joinColumn, $queryBuilder);

        $queryBuilder = $this->addOrder($queryBuilder, $criteria);

        $query = $queryBuilder->getQuery();

        $query = $this->createQueryMode($query, $criteria);

        return $query->getResult();
    }

    /**
     * array joinColumn array($join, $alias, $conditionType, $condition, $indexBy)
     * @param array $criteria
     * @param array $joinColumn
     * @return
     */
    public function findOneByCriteria(array $criteria = [], array $joinColumn = [])
    {
        $queryBuilder = $this->createQueryBuilder('entity');

        $queryBuilder = $this->addWhere($queryBuilder, $criteria);

        $queryBuilder = $this->createJoin($joinColumn, $queryBuilder);

        $query = $queryBuilder->getQuery();

        $query = $this->createQueryMode($query, $criteria);

        return $query->getOneOrNullResult();
    }

    private function addWhere(QueryBuilder $queryBuilder, array $criteria)
    {
        foreach ($criteria as $key => $value) {
            if (!in_array($key, self::$unauthorizedKeys)) {
                $queryBuilder
                    ->andWhere('entity.' . $key . ' = :' . $key)
                    ->setParameter($key, $value);
            }
        }
        return $queryBuilder;
    }

    public function addOrder(QueryBuilder $queryBuilder, array $criteria)
    {
        if (isset($criteria['asc'])) {
            $queryBuilder->addOrderBy('entity.' . $criteria['asc'], 'ASC');
        }
        if (isset($criteria['desc'])) {
            $queryBuilder->addOrderBy('entity.' . $criteria['desc'], 'DESC');
        }
        if (isset($criteria['offset'])) {
            $queryBuilder->setFirstResult($criteria['offset']);
        }
        if (isset($criteria['limit'])) {
            $queryBuilder->setMaxResults($criteria['limit']);
        }
        return $queryBuilder;
    }


    protected function createJoin($joinColumn, QueryBuilder $queryBuilder)
    {
        foreach ($joinColumn as $join) {
            if (!is_array($join)) {
                $join = array(
                    'join' => $join,
                    'alias' => substr(uniqid('', true), -5),
                    'conditionType' => null,
                    'condition' => null,
                    'indexBy' => null
                );
            }

            $this->makeSelectJoin($queryBuilder, $join);
        }
        return $queryBuilder;
    }

    private function makeSelectJoin(QueryBuilder $queryBuilder, array $join)
    {
        if (isset($join['join']) && isset($join['alias'])) {
            $queryBuilder
                ->addSelect($join['alias'])
                ->leftJoin(
                    (isset($join['leftJoin']) ? $join['leftJoin'] : 'entity') . '.' . $join['join'],
                    $join['alias'],
                    isset($join['conditionType']) ? $join['conditionType'] : null,
                    isset($join['condition']) ? $join['condition'] : null,
                    isset($join['alias']) && isset($join['indexBy']) ?
                        $join['alias'] . '.' . $join['indexBy'] : null
                );
        }
        return $queryBuilder;
    }

    protected function createQueryMode(Query $query, array $criteria)
    {
        if (isset($criteria['hint'])) {
            $query->setHint($criteria['hint'], true);
        }
        if (isset($criteria['partial_load'])) {
            $query->setHint(Query::HINT_FORCE_PARTIAL_LOAD, true);
        }
        if (isset($criteria['hydrate'])) {
            return $query->getOneOrNullResult($criteria['hydrate']);
        }

        return $query;
    }
}
