<?php

namespace App\Repository;

use Doctrine\ORM\Query;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends AbstractEntityRepository
{
    public function findCitiesByIds(array $cities)
    {
        $query = $this->createQueryBuilder('entity');
        $query
            ->select('partial entity.{id, title}')
            ->andWhere('entity.id IN (:cities)')
            ->setParameter('cities', $cities);

        return $query->getQuery()->getResult(Query::HYDRATE_ARRAY);
    }

    public function findPreBookingCitiesBy($criteria)
    {
        $query = $this->createQueryBuilder('entity');
        $query
            ->select('partial entity.{id, title, googleId}')
            ->leftJoin('entity.adverts', 'advert')
            ->andWhere('advert.statut = 1');

        if (isset($criteria['advert'])) {
            $query
                ->andWhere('advert.id = :advert')
                ->setParameter('advert', $criteria['advert']);
        }

        return $query->getQuery()->getResult(Query::HYDRATE_ARRAY);
    }
}
