<?php

namespace App\Repository;

use Doctrine\ORM\Query;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends AbstractEntityRepository
{
    public function findCommentsByStatus(string $status)
    {
        $query = $this->createQueryBuilder('entity');
        $query
            ->select('entity.comment, entity.createdAt, user.firstName, user.lastName')
            ->leftJoin('entity.user', 'user')
            ->andWhere('entity.status = :status')
            ->setParameter('status', $status);

        return $query->getQuery()->getResult();
    }
}
