<?php

namespace App\Repository;

/**
 * FamilyTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyTranslationRepository extends AbstractEntityRepository
{
}
