<?php

namespace App\Repository;

/**
 * FamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyRepository extends AbstractEntityRepository
{
    public function findSubFamiliesByParent($family)
    {
        $query = $this->createQueryBuilder('entity');
        $query
            ->select('entity')
            ->addSelect('t')
            ->leftJoin('entity.sports', 's')
            ->leftJoin('entity.translations', 't', 'WITH', 't.family = entity.id', 't.locale')
            ->leftJoin('s.advert', 'ads')
            ->leftJoin('entity.children', 'c')
            ->andWhere('entity.parent = :family')
            ->setParameter('family', $family)
            ->addGroupBy('entity.id')
            // ->having($query->expr()->count('ads.id') . ' > 0')
            ->setMaxResults(9);

        return $query->getQuery()->getResult();
    }
}
