<?php

namespace App\Repository;

/**
 * LanguageTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
