<?php

namespace App\Repository;

/**
 * SportTeachedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends AbstractEntityRepository
{
    public function findLikeFilename($filename)
    {
        $query = $this->createQueryBuilder('entity');

        $query
            ->andWhere('entity.filename LIKE :filename')
            ->setParameter('filename', $filename . '%');

        return $query->getQuery()->getResult();
    }
}
