<?php

namespace App\Repository;

/**
 * OfferTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
