<?php

namespace App\Repository;

/**
 * PassionTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassionTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
