<?php

namespace App\Repository;

/**
 * SportTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportTranslationRepository extends AbstractEntityRepository
{
    public function findSportsTranslationsByLevel($level)
    {
        $query = $this->createQueryBuilder('entity');
        $query
            ->select('sport.id, entity.title, entity.locale')
            ->leftJoin('entity.sport', 'sport')
            ->andWhere('sport.level =:level')
            ->setParameter('level', $level);

        return $query->getQuery()->getResult();
    }
}
