FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
      id:
        expose: true
      email:
        expose: true
      enabled:
        expose: true
      lastLogin:
        expose: true
      roles:
        expose: true