admin_user:
  type: rest
  resource:     "@AppBundle/Controller/Admin/UserController.php"
  name_prefix:  admin_
  prefix: admin

admin_advert:
  type: rest
  resource:     "@AppBundle/Controller/Admin/AdvertController.php"
  name_prefix:  admin_
  prefix: admin

admin_comment:
  type: rest
  resource:     "@AppBundle/Controller/Admin/CommentController.php"
  name_prefix:  admin_
  prefix: admin

admin_sport:
  type: rest
  resource:     "@AppBundle/Controller/Admin/SportController.php"
  name_prefix:  admin_
  prefix: admin

admin_family:
  type: rest
  resource:     "@AppBundle/Controller/Admin/FamilyController.php"
  name_prefix:  admin_
  prefix: admin

admin_booking:
  type: rest
  resource:     "@AppBundle/Controller/Admin/BookingController.php"
  name_prefix:  admin_
  prefix: admin

admin_form:
  type: rest
  resource:     "@AppBundle/Controller/Admin/FormController.php"
  name_prefix:  admin_
  prefix: admin