front_address:
  type: rest
  resource: "@AppBundle/Controller/Front/AddressController.php"

front_email_reminder:
  type: rest
  resource: "@AppBundle/Controller/Front/EmailReminderController.php"

front_advert:
  type: rest
  resource: "@AppBundle/Controller/Front/AdvertController.php"

front_advert_sport:
  type: rest
  resource: "@AppBundle/Controller/Front/AdvertSportController.php"

front_advert_sport_translation:
  type: rest
  resource: "@AppBundle/Controller/Front/AdvertSportTranslationController.php"

front_advert_translation:
  type: rest
  resource: "@AppBundle/Controller/Front/AdvertSportTranslationController.php"

front_prebooking:
  type: rest
  resource: "@AppBundle/Controller/Front/PreBookingController.php"
  prefix: prebookings

front_booking:
  type: rest
  resource: "@AppBundle/Controller/Front/BookingController.php"
  prefix: bookings

front_city:
  type: rest
  resource: "@AppBundle/Controller/Front/CityController.php"

front_comment:
  type: rest
  resource: "@AppBundle/Controller/Front/CommentController.php"

front_family:
  type: rest
  resource: "@AppBundle/Controller/Front/FamilyController.php"

front_diploma:
  type: rest
  resource: "@AppBundle/Controller/Front/DiplomaController.php"

front_image:
  type: rest
  resource: "@AppBundle/Controller/Front/ImageController.php"

front_meeting:
  type: rest
  resource: "@AppBundle/Controller/Front/MeetingController.php"

front_phone:
  type: rest
  resource: "@AppBundle/Controller/Front/PhoneController.php"

front_sport:
  type: rest
  resource: "@AppBundle/Controller/Front/SportController.php"

front_sport_translation:
  type: rest
  resource: "@AppBundle/Controller/Front/SportTranslationController.php"

front_structure:
  type: rest
  resource: "@AppBundle/Controller/Front/StructureController.php"

front_user:
  type: rest
  resource: "@AppBundle/Controller/Front/UserController.php"

front_search:
  type: rest
  resource: "@AppBundle/Controller/Front/SearchController.php"